version: '3'
# Debug version of ContinuITy
services:
  eureka:
    image: continuityproject/eureka
    hostname: eureka
    networks:
      - continuity-network
    ports:
      - '8761:8761'
  frontend:
    image: continuityproject/frontend
    hostname: frontend
    networks:
      - continuity-network
    ports:
      - '8080:80'
      - '5000:5000'

    depends_on:
      - rabbitmq
      - eureka

    entrypoint:
      - java
      - -Xdebug
      - -Xnoagent
      - -Djava.compiler=NONE
      - -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5000
      - -jar
      - /app.jar
      - --port=80
      - --spring.rabbitmq.host=rabbitmq
      - --eureka.uri=http://eureka:8761/eureka

  rabbitmq:
    image: rabbitmq:3.6.8-management
    hostname: rabbitmq
    networks:
      - continuity-network
    ports:
      - '15672:15672'

  workload-annotation:
    image: continuityproject/workload-annotation
    hostname: workload-annotation
    networks:
      - continuity-network
    ports:
      - '8081:80'
      - '5001:5000'

    depends_on:
      - rabbitmq
      - eureka

    entrypoint:
      - java
      - -Xdebug
      - -Xnoagent
      - -Djava.compiler=NONE
      - -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5000
      - -jar
      - /app.jar
      - --port=80
      - --spring.rabbitmq.host=rabbitmq
      - --eureka.uri=http://eureka:8761/eureka
      - --storage.path=/storage

  wessbas:
    image: continuityproject/wessbas
    hostname: wessbas
    networks:
      - continuity-network
    ports:
      - '8082:80'
      - '5002:5000'

    depends_on:
      - rabbitmq
      - eureka

    entrypoint:
      - java
      - -Xdebug
      - -Xnoagent
      - -Djava.compiler=NONE
      - -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5000
      - -jar
      - /app.jar
      - --port=80
      - --spring.rabbitmq.host=rabbitmq
      - --eureka.uri=http://eureka:8761/eureka

  jmeter:
    image: continuityproject/jmeter
    hostname: jmeter
    networks:
      - continuity-network
    ports:
      - '8083:80'
      - '5003:5000'

    depends_on:
      - rabbitmq
      - eureka

    entrypoint:
      - java
      - -Xdebug
      - -Xnoagent
      - -Djava.compiler=NONE
      - -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5000
      - -jar
      - /bin/app.jar
      - --port=80
      - --spring.rabbitmq.host=rabbitmq
      - --eureka.uri=http://eureka:8761/eureka

  session-logs:
    image: continuityproject/session-logs
    hostname: session-logs
    networks:
      - continuity-network
    ports:
      - '8084:80'
      - '5004:5000'

    depends_on:
      - rabbitmq
      - eureka

    entrypoint:
      - java
      - -Xdebug
      - -Xnoagent
      - -Djava.compiler=NONE
      - -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5000
      - -jar
      - /app.jar
      - --port=80
      - --eureka.uri=http://eureka:8761/eureka

networks:
  continuity-network:
    driver: bridge
